[package]
name = "nordic_grid"
version = "0.1.0"
edition = "2021"

[dependencies]
ggez = "0.9.3"
rand = "0.7.3"
serde_json = "1.0.120"
serde = "1.0.204"
sdl2 = { version = "0.37.0", features=["bundled"] }
